set firewall global-options all-ping 'enable'
set firewall global-options broadcast-ping 'disable'
set firewall global-options directed-broadcast 'enable'
set firewall global-options ip-src-route 'disable'
set firewall global-options ipv6-receive-redirects 'disable'
set firewall global-options ipv6-source-validation 'disable'
set firewall global-options ipv6-src-route 'disable'
set firewall global-options log-martians 'enable'
set firewall global-options send-redirects 'enable'
set firewall global-options source-validation 'disable'
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy invalid log
set firewall global-options state-policy related action 'accept'
set firewall global-options syn-cookies 'enable'
set firewall global-options twa-hazards-protection 'disable'
set firewall group address-group ADMIN address '10.10.10.5'
set firewall group address-group ADMIN address '10.10.10.10'
set firewall group address-group ADMIN address '10.10.20.5'
set firewall group address-group ADMIN address '10.10.20.10'
set firewall group address-group ADMIN address '10.10.88.3'
set firewall group address-group ADMIN description '##### FULL ACCESS ADMIN CLIENTS #####'
set firewall group address-group NONVPN-SRC address '10.10.10.50'
set firewall group address-group NONVPN-SRC address '10.10.10.55'
set firewall group address-group NONVPN-SRC address '10.10.20.50'
set firewall group address-group NONVPN-SRC address '10.10.20.55'
set firewall group address-group NONVPN-SRC address '10.10.20.60'
set firewall group address-group NONVPN-SRC description '##### NON VPN SOURCE ADDRESSES #####'
set firewall group network-group NONVPN-DEST description '##### NON VPN DESTINATION NETWORKS #####'
set firewall group network-group NONVPN-DEST network '1.1.1.0/24'
set firewall group network-group NONVPN-DEST network '2.2.2.0/27'
set firewall group network-group NONVPN-DEST network '3.3.3.0/27'
set firewall group network-group NONVPN-DEST network '4.4.4.0/24'
set firewall group network-group RFC1918 description '##### RFC1918 NETWORKS #####'
set firewall group network-group RFC1918 network '192.168.0.0/16'
set firewall group network-group RFC1918 network '172.16.0.0/12'
set firewall group network-group RFC1918 network '10.0.0.0/8'
set firewall ipv4 forward filter default-action 'drop'
set firewall ipv4 forward filter default-log
set firewall ipv4 forward filter rule 10 action 'accept'
set firewall ipv4 forward filter rule 10 description '##### ALLOW ADMIN CLIENTS FULL ACCESS #####'
set firewall ipv4 forward filter rule 10 destination group network-group 'RFC1918'
set firewall ipv4 forward filter rule 10 source group address-group 'ADMIN'
set firewall ipv4 forward filter rule 20 action 'accept'
set firewall ipv4 forward filter rule 20 description '##### ALLOW LOCAL DNS ACCESS #####'
set firewall ipv4 forward filter rule 20 destination address '10.10.10.2'
set firewall ipv4 forward filter rule 20 destination port '53'
set firewall ipv4 forward filter rule 20 protocol 'udp'
set firewall ipv4 forward filter rule 20 source group network-group 'RFC1918'
set firewall ipv4 forward filter rule 30 action 'drop'
set firewall ipv4 forward filter rule 30 description '##### BLOCK UNTRUSTED INTERNET ACCESS VIA VPN #####'
set firewall ipv4 forward filter rule 30 destination address '0.0.0.0/0'
set firewall ipv4 forward filter rule 30 outbound-interface name 'wg1'
set firewall ipv4 forward filter rule 30 source address '10.10.30.0/24'
set firewall ipv4 forward filter rule 31 action 'drop'
set firewall ipv4 forward filter rule 31 description '##### BLOCK UNTRUSTED INTERNET ACCESS VIA WAN #####'
set firewall ipv4 forward filter rule 31 destination address '0.0.0.0/0'
set firewall ipv4 forward filter rule 31 outbound-interface name 'eth1'
set firewall ipv4 forward filter rule 31 source address '10.10.30.0/24'
set firewall ipv4 forward filter rule 40 action 'accept'
set firewall ipv4 forward filter rule 40 description '##### ALLOW INTERNET ACCESS VIA VPN #####'
set firewall ipv4 forward filter rule 40 destination address '0.0.0.0/0'
set firewall ipv4 forward filter rule 40 outbound-interface name 'wg1'
set firewall ipv4 forward filter rule 40 source group network-group 'RFC1918'
set firewall ipv4 forward filter rule 41 action 'accept'
set firewall ipv4 forward filter rule 41 description '##### ALLOW INTERNET ACCESS VIA WAN #####'
set firewall ipv4 forward filter rule 41 destination address '0.0.0.0/0'
set firewall ipv4 forward filter rule 41 outbound-interface name 'eth1'
set firewall ipv4 forward filter rule 41 source group network-group 'RFC1918'
set firewall ipv4 forward filter rule 50 action 'accept'
set firewall ipv4 forward filter rule 50 description '##### ALLOW LOCAL REVERSE PROXY ACCESS #####'
set firewall ipv4 forward filter rule 50 destination address '10.10.10.3'
set firewall ipv4 forward filter rule 50 destination port '443'
set firewall ipv4 forward filter rule 50 protocol 'tcp'
set firewall ipv4 forward filter rule 50 source group network-group 'RFC1918'
set firewall ipv4 forward filter rule 51 action 'accept'
set firewall ipv4 forward filter rule 51 description '##### ALLOW LOCAL ACCESS TO EMBY #####'
set firewall ipv4 forward filter rule 51 destination address '10.10.10.30'
set firewall ipv4 forward filter rule 51 destination port '8096'
set firewall ipv4 forward filter rule 51 protocol 'tcp'
set firewall ipv4 forward filter rule 51 source group network-group 'RFC1918'
set firewall ipv4 forward filter rule 60 action 'accept'
set firewall ipv4 forward filter rule 60 description '##### ALLOW CLOUD REVERSE PROXY OVER WIREGUARD TO EMBY #####'
set firewall ipv4 forward filter rule 60 destination address '10.10.10.30'
set firewall ipv4 forward filter rule 60 destination port '8096'
set firewall ipv4 forward filter rule 60 protocol 'tcp'
set firewall ipv4 forward filter rule 60 source address '10.10.88.2'
set firewall ipv4 forward filter rule 61 action 'accept'
set firewall ipv4 forward filter rule 61 description '##### ALLOW CLOUD REVERSE PROXY OVER WIREGUARD TO JELLYSEERR #####'
set firewall ipv4 forward filter rule 61 destination address '10.10.10.35'
set firewall ipv4 forward filter rule 61 destination port '5055'
set firewall ipv4 forward filter rule 61 protocol 'tcp'
set firewall ipv4 forward filter rule 61 source address '10.10.88.2'
set firewall ipv4 forward filter rule 110 action 'accept'
set firewall ipv4 forward filter rule 110 description '##### ISOLATE VLAN 10 - LAN NETWORK #####'
set firewall ipv4 forward filter rule 110 destination address '10.10.10.0/24'
set firewall ipv4 forward filter rule 110 source address '10.10.10.0/24'
set firewall ipv4 forward filter rule 120 action 'accept'
set firewall ipv4 forward filter rule 120 description '##### ISOLATE VLAN 20 - WIFI NETWORK #####'
set firewall ipv4 forward filter rule 120 destination address '10.10.20.0/24'
set firewall ipv4 forward filter rule 120 source address '10.10.20.0/24'
set firewall ipv4 forward filter rule 130 action 'accept'
set firewall ipv4 forward filter rule 130 description '##### ISOLATE VLAN 30 - UNTRUSTED NETWORK #####'
set firewall ipv4 forward filter rule 130 destination address '10.10.30.0/24'
set firewall ipv4 forward filter rule 130 source address '10.10.30.0/24'
set firewall ipv4 forward filter rule 180 action 'accept'
set firewall ipv4 forward filter rule 180 description '##### ISOLATE VLAN 80 - MANAGEMENT NETWORK #####'
set firewall ipv4 forward filter rule 180 destination address '10.10.80.0/24'
set firewall ipv4 forward filter rule 180 source address '10.10.80.0/24'
set firewall ipv4 forward filter rule 188 action 'accept'
set firewall ipv4 forward filter rule 188 description '##### ISOLATE VLAN 88 - WIREGUARD NETWORK #####'
set firewall ipv4 forward filter rule 188 destination address '10.10.88.0/24'
set firewall ipv4 forward filter rule 188 source address '10.10.88.0/24'
set firewall ipv4 forward filter rule 300 action 'accept'
set firewall ipv4 forward filter rule 300 description '##### ACCEPT XBOX LIVE #####'
set firewall ipv4 forward filter rule 300 destination address '10.10.10.40'
set firewall ipv4 forward filter rule 300 destination port '50029'
set firewall ipv4 forward filter rule 300 log
set firewall ipv4 forward filter rule 300 protocol 'tcp_udp'
set firewall ipv4 forward filter rule 301 action 'accept'
set firewall ipv4 forward filter rule 301 description '##### ALLOW PLAYSTATION PLUS TCP #####'
set firewall ipv4 forward filter rule 301 destination address '10.10.10.45'
set firewall ipv4 forward filter rule 301 destination port '3478-3480'
set firewall ipv4 forward filter rule 301 log
set firewall ipv4 forward filter rule 301 protocol 'tcp'
set firewall ipv4 forward filter rule 302 action 'accept'
set firewall ipv4 forward filter rule 302 description '##### ALLOW PLAYSTATION PLUS UDP #####'
set firewall ipv4 forward filter rule 302 destination address '10.10.10.45'
set firewall ipv4 forward filter rule 302 destination port '3478-3479'
set firewall ipv4 forward filter rule 302 log
set firewall ipv4 forward filter rule 302 protocol 'udp'
set firewall ipv4 input filter default-action 'drop'
set firewall ipv4 input filter default-log
set firewall ipv4 input filter rule 10 action 'accept'
set firewall ipv4 input filter rule 10 description '##### ALLOW ADMIN CLIENTS LOCAL ACCESS #####'
set firewall ipv4 input filter rule 10 source group address-group 'ADMIN'
set firewall ipv4 input filter rule 110 action 'accept'
set firewall ipv4 input filter rule 110 description '##### ALLOW VLAN 10 - LAN LOCAL ACCESS #####'
set firewall ipv4 input filter rule 110 destination address '10.10.10.1'
set firewall ipv4 input filter rule 110 source address '10.10.10.0/24'
set firewall ipv4 input filter rule 120 action 'accept'
set firewall ipv4 input filter rule 120 description '##### ALLOW VLAN 20 - WIFI LOCAL ACCESS #####'
set firewall ipv4 input filter rule 120 destination address '10.10.20.1'
set firewall ipv4 input filter rule 120 source address '10.10.20.0/24'
set firewall ipv4 input filter rule 130 action 'accept'
set firewall ipv4 input filter rule 130 description '##### ALLOW VLAN 30 - UNTRUSTED LOCAL ACCESS #####'
set firewall ipv4 input filter rule 130 destination address '10.10.30.1'
set firewall ipv4 input filter rule 130 source address '10.10.30.0/24'
set firewall ipv4 input filter rule 180 action 'accept'
set firewall ipv4 input filter rule 180 description '##### ALLOW VLAN 80 - MANAGEMENT LOCAL ACCESS #####'
set firewall ipv4 input filter rule 180 destination address '10.10.80.1'
set firewall ipv4 input filter rule 180 source address '10.10.80.0/24'
set firewall ipv4 input filter rule 188 action 'accept'
set firewall ipv4 input filter rule 188 description '##### ALLOW VLAN 88 - WIREGUARD LOCAL ACCESS #####'
set firewall ipv4 input filter rule 188 destination address '10.10.88.1'
set firewall ipv4 input filter rule 188 source address '10.10.88.0/24'
set interfaces bonding bond0 member interface 'eth0'
set interfaces bonding bond0 member interface 'eth4'
set interfaces bonding bond0 vif 10 address '10.10.10.1'
set interfaces bonding bond0 vif 10 description 'VLAN10 - LAN'
set interfaces bonding bond0 vif 20 address '10.10.20.1'
set interfaces bonding bond0 vif 20 description 'VLAN20 - WIFI'
set interfaces bonding bond0 vif 30 address '10.10.30.1'
set interfaces bonding bond0 vif 30 description 'VLAN30 - UNTRUSTED
set interfaces bonding bond0 vif 80 address '10.10.80.1'
set interfaces bonding bond0 vif 80 description 'VLAN80 - MANAGEMENT'
set interfaces ethernet eth0 offload gro
set interfaces ethernet eth0 offload gso
set interfaces ethernet eth0 offload lro
set interfaces ethernet eth0 offload rfs
set interfaces ethernet eth0 offload rps
set interfaces ethernet eth0 offload sg
set interfaces ethernet eth0 offload tso
set interfaces ethernet eth4 offload gro
set interfaces ethernet eth4 offload gso
set interfaces ethernet eth4 offload rfs
set interfaces ethernet eth4 offload rps
set interfaces ethernet eth4 offload sg
set interfaces ethernet eth4 offload tso
set interfaces ethernet eth1 address '1.2.3.2/30'
set interfaces ethernet eth1 description 'WAN'
set interfaces ethernet eth1 offload rfs
set interfaces ethernet eth1 offload rps
set interfaces ethernet eth1 offload sg
set interfaces wireguard wg0 address '10.10.88.1'
set interfaces wireguard wg0 description 'PUBLIC REVERSE PROXY'
set interfaces wireguard wg0 peer HETZNER address '4.3.2.1'
set interfaces wireguard wg0 peer HETZNER allowed-ips '10.10.88.0/24'
set interfaces wireguard wg0 peer HETZNER persistent-keepalive '20'
set interfaces wireguard wg0 peer HETZNER port '51820'
set interfaces wireguard wg0 peer HETZNER preshared-key '<HETZNER-PSK>'
set interfaces wireguard wg0 peer HETZNER public-key '<HETZNER-PUBKEY>'
set interfaces wireguard wg0 private-key '<HETZNER-PRIVKEY>'
set interfaces wireguard wg1 address '10.2.0.2/32'
set interfaces wireguard wg1 description 'PROTONVPN'
set interfaces wireguard wg1 peer CH-NL address '5.6.7.8'
set interfaces wireguard wg1 peer CH-NL allowed-ips '0.0.0.0/0'
set interfaces wireguard wg1 peer CH-NL persistent-keepalive '20'
set interfaces wireguard wg1 peer CH-NL port '51820'
set interfaces wireguard wg1 peer CH-NL public-key '<PROTONVPN-PUBKEY>'
set interfaces wireguard wg1 private-key '<PROTONVPN-PRIVKEY>'
set nat destination rule 100 description 'XBox Live'
set nat destination rule 100 destination port '50029'
set nat destination rule 100 inbound-interface name 'eth1'
set nat destination rule 100 protocol 'tcp_udp'
set nat destination rule 100 translation address '10.10.10.40'
set nat destination rule 101 description 'PlayStation Plus TCP'
set nat destination rule 101 destination port '3478-3480'
set nat destination rule 101 inbound-interface name 'eth1'
set nat destination rule 101 protocol 'tcp'
set nat destination rule 101 translation address '10.10.10.45'
set nat destination rule 102 description 'PlayStation Plus UDP'
set nat destination rule 102 destination port '3478-3479'
set nat destination rule 102 inbound-interface name 'eth1'
set nat destination rule 102 protocol 'udp'
set nat destination rule 102 translation address '10.10.10.45'
set nat source rule 100 log
set nat source rule 100 outbound-interface name 'eth1'
set nat source rule 100 translation address 'masquerade'
set nat source rule 101 log
set nat source rule 101 outbound-interface name 'wg1'
set nat source rule 101 translation address 'masquerade'
set policy route VPN interface 'bond0.10'
set policy route VPN interface 'bond0.20'
set policy route VPN interface 'bond0.30'
set policy route VPN interface 'bond0.80'
set policy route VPN rule 10 destination group network-group 'RFC1918'
set policy route VPN rule 10 set table 'main'
set policy route VPN rule 20 set table 'main'
set policy route VPN rule 20 source group address-group 'NONVPN-SRC'
set policy route VPN rule 30 destination group network-group 'NONVPN-DEST'
set policy route VPN rule 30 set table 'main'
set policy route VPN rule 100 destination address '0.0.0.0/0'
set policy route VPN rule 100 set table '100'
set policy route VPN rule 100 source group network-group 'RFC1918'
set protocols static route 0.0.0.0/0 next-hop 1.2.3.1 
set protocols static table 100 route 0.0.0.0/0 blackhole distance '254'
set protocols static table 100 route 0.0.0.0/0 interface wg1 distance '1'
set service lldp interface all
set service lldp legacy-protocols cdp
set service lldp management-address '10.10.80.1'
set service ntp server 0.us.pool.ntp.org
set service ntp server 1.us.pool.ntp.org
set service ssh listen-address '10.10.80.1'
set service ssh port '22025'
set system config-management commit-revisions '100'
set system console device ttyS0 speed '115200'
set system host-name 'vyos'
set system ipv6 disable-forwarding
set system login banner post-login '\nWELCOME TO THE FIREWALL!\n'
set system login banner pre-login '\nNO UNAUTHORIZED ACCESS!\n'
set system login user vyos authentication public-keys YK5NFC-GREEN key '<PUBLIC-KEY>'
set system login user vyos authentication public-keys YK5NFC-GREEN type 'sk-ssh-ed25519@openssh.com'
set system login user vyos authentication public-keys YK5NFC-RED key '<PUBLIC-KEY>'
set system login user vyos authentication public-keys YK5NFC-RED type 'sk-ssh-ed25519@openssh.com'
set system login user vyos authentication public-keys WORKSTATION key '<PUBLIC-KEY>'
set system login user vyos authentication public-keys WORKSTATION type 'ssh-ed25519'
set system name-server '9.9.9.9'
set system name-server '149.112.112.112'
set system option performance 'network-throughput'
set system option performance 'network-latency'
set system option time-format '24-hour'
set system syslog local facility all level 'info'
set system syslog local facility local7 level 'debug'
set system time-zone 'America/Chicago'
set system update-check auto-check
set system update-check url 'https://raw.githubusercontent.com/vyos/vyos-rolling-nightly-builds/main/version.json'
